import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { portraits } from "../src/data/portraits";
import {
  characterById,
  characters,
  entityHref,
  entityName,
  events,
  factionById,
  factions,
  glossary,
  knowledgeFacts,
  locations,
  mysteries,
  nenAbilities,
  princes,
  sortedChapters,
  storylines,
  theories,
} from "../src/lib/db";
import { ARC_END } from "../src/lib/types";

const root = resolve(import.meta.dirname, "..");
const generatedDir = resolve(root, "src/generated");
mkdirSync(generatedDir, { recursive: true });

function ordinal(n: number): string {
  const suffixes = ["th", "st", "nd", "rd"];
  const remainder = n % 100;
  return (
    n + (suffixes[(remainder - 20) % 10] ?? suffixes[remainder] ?? suffixes[0])
  );
}

const entityIds = new Set<string>([
  ...characters.map((item) => item.id),
  ...princes.map((item) => item.id),
  ...factions.map((item) => item.id),
  ...locations.map((item) => item.id),
  ...nenAbilities.map((item) => item.id),
  ...storylines.map((item) => item.id),
  ...mysteries.map((item) => item.id),
  ...theories.map((item) => item.id),
  ...knowledgeFacts.map((item) => item.id),
]);

const entityIndex = Object.fromEntries(
  [...entityIds].map((id) => {
    const character = characterById.get(id);
    const faction = factionById.get(id);
    const primaryFaction = character?.factionIds[0]
      ? factionById.get(character.factionIds[0])
      : undefined;
    const portrait = portraits[id]?.replace(
      "/portraits/",
      "/portraits/thumbs/",
    );
    return [
      id,
      {
        name: entityName(id),
        href: entityHref(id),
        color: faction?.color ?? (character ? "var(--ivory)" : "var(--teal)"),
        frameColor: primaryFaction?.color ?? "var(--gold-dim)",
        monogram: character?.monogram,
        ...(portrait ? { portrait } : {}),
      },
    ];
  }),
);

const entitySource = `/* Generated by scripts/generate-client-indexes.ts. Do not edit. */
export interface EntityIndexEntry {
  name: string;
  href: string;
  color: string;
  frameColor: string;
  monogram?: string;
  portrait?: string;
}

export const entityIndex: Record<string, EntityIndexEntry> = ${JSON.stringify(entityIndex)};
`;

interface SearchItem {
  id: string;
  label: string;
  sub: string;
  kind: string;
  href: string;
  hay: string;
  revealCh: number;
}

const searchIndex: SearchItem[] = [];
for (const character of characters) {
  searchIndex.push({
    id: character.id,
    label: character.name,
    sub: character.role,
    kind: "Character",
    href: `/characters/${character.id}`,
    hay: `${character.name} ${(character.aliases ?? []).join(" ")} ${character.role} ${(character.tags ?? []).join(" ")}`.toLowerCase(),
    revealCh: character.introducedCh,
  });
}
for (const prince of princes) {
  const character = characterById.get(prince.characterId);
  searchIndex.push({
    id: prince.id,
    label: `Prince ${character?.name ?? prince.characterId}`,
    sub: `${ordinal(prince.rank)} Prince of Kakin`,
    kind: "Prince",
    href: `/princes/${prince.id}`,
    hay: `prince ${character?.name} ${ordinal(prince.rank)} ${prince.motherName}`.toLowerCase(),
    revealCh: 358,
  });
}
for (const faction of factions) {
  searchIndex.push({
    id: faction.id,
    label: faction.name,
    sub: "Faction",
    kind: "Faction",
    href: `/factions/${faction.id}`,
    hay: faction.name.toLowerCase(),
    revealCh: faction.introducedCh,
  });
}
for (const chapter of sortedChapters) {
  searchIndex.push({
    id: `ch-${chapter.number}`,
    label: `Chapter ${chapter.number}: ${chapter.title}`,
    sub: chapter.summary.slice(0, 80),
    kind: "Chapter",
    href: `/chapters/${chapter.number}`,
    hay: `chapter ${chapter.number} ${chapter.title} ${chapter.summary}`.toLowerCase(),
    revealCh: chapter.number,
  });
}
for (const ability of nenAbilities) {
  searchIndex.push({
    id: ability.id,
    label: ability.name,
    sub: `Nen · ${ability.nenType}`,
    kind: "Ability",
    href: `/nen/${ability.id}`,
    hay: `${ability.name} ${ability.description} ${ability.nenType}`.toLowerCase(),
    revealCh: ability.revealCh,
  });
}
for (const location of locations) {
  searchIndex.push({
    id: location.id,
    label: location.name,
    sub: `Location${location.tier ? ` · Tier ${location.tier}` : ""}`,
    kind: "Location",
    href: `/map?location=${location.id}`,
    hay: location.name.toLowerCase(),
    revealCh: location.introducedCh,
  });
}
for (const storyline of storylines) {
  searchIndex.push({
    id: storyline.id,
    label: storyline.name,
    sub: "Storyline",
    kind: "Storyline",
    href: `/storylines/${storyline.id}`,
    hay: storyline.name.toLowerCase(),
    revealCh: storyline.introducedCh,
  });
}
for (const event of events) {
  searchIndex.push({
    id: event.id,
    label: event.title,
    sub: `Event · Ch.${event.chapter}`,
    kind: "Event",
    href: `/timeline?event=${event.id}`,
    hay: `${event.title} ${event.summary}`.toLowerCase(),
    revealCh: event.chapter,
  });
}
for (const mystery of mysteries) {
  searchIndex.push({
    id: mystery.id,
    label: mystery.question,
    sub: "Mystery",
    kind: "Mystery",
    href: `/mysteries#${mystery.id}`,
    hay: mystery.question.toLowerCase(),
    revealCh: mystery.introducedCh,
  });
}
for (const theory of theories) {
  searchIndex.push({
    id: theory.id,
    label: theory.claim,
    sub: "Theory",
    kind: "Theory",
    href: `/theories#${theory.id}`,
    hay: theory.claim.toLowerCase(),
    revealCh: Math.min(...theory.chapters, ARC_END),
  });
}
for (const term of glossary) {
  searchIndex.push({
    id: term.id,
    label: term.term,
    sub: "Glossary",
    kind: "Term",
    href: `/glossary#${term.id}`,
    hay: `${term.term} ${term.definition}`.toLowerCase(),
    revealCh: term.introducedCh,
  });
}
for (const fact of knowledgeFacts) {
  searchIndex.push({
    id: fact.id,
    label: fact.label,
    sub: "Intel fact",
    kind: "Fact",
    href: `/knowledge?fact=${fact.id}`,
    hay: `${fact.label} ${fact.description}`.toLowerCase(),
    revealCh: fact.readerRevealCh,
  });
}

const searchSource = `/* Generated by scripts/generate-client-indexes.ts. Do not edit. */
export interface SearchItem {
  id: string;
  label: string;
  sub: string;
  kind: string;
  href: string;
  hay: string;
  revealCh: number;
}

export const searchIndex: SearchItem[] = ${JSON.stringify(searchIndex)};
`;

writeFileSync(resolve(generatedDir, "entityIndex.ts"), entitySource);
writeFileSync(resolve(generatedDir, "searchIndex.ts"), searchSource);

console.log(
  `Generated ${Object.keys(entityIndex).length} entities and ${searchIndex.length} search records.`,
);
